---
galaxy_info:
  author: Valentin Gostev
  description: Ansible role deploys Minio container
  role_name: ct_minio
  namespace: almaops
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - minio
    - object
    - storage
    - s3
dependencies: []
...
