---
galaxy_info:
  author: Valentin Gostev
  description: Ansible role for deploying PostgreSQL container
  role_name: ct_postgres
  namespace: almaops
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - postgres
    - postgresql
    - database
    - databases
    - psql
    - rdbms
allow_duplicates: false
dependencies: []
...
