---
galaxy_info:
  author: Dmitrii Kashin
  description: Loading ansible variables from files
  role_name: var
  namespace: almaops
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - variables
    - environment
dependencies: []
...
