---
galaxy_info:
  author: Dmitrii Kashin
  role_name: user
  namespace: almaops
  description: Create and manage users on Debian-like systems
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - system
    - user
dependencies: []
...
